// Three setups on the 45 public purchases: no control, a plain spending limit, and our engine.
//   npm run compare            -> docs/pitch/comparison.md and docs/pitch/comparison.svg
// "Risky" = the reference says the purchase needs a refusal or a question. The reference file is read here only,
// for scoring; the engine never sees it (see replay.ts).
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { DATA_DIR, loadDataPack, readCsv, scenarioAttempts } from "../../shared/src/loaders";
import { buildEvent } from "../../shared/src/csvEvent";
import { compilePolicy } from "../../shared/src/compiler";
import { replayScenario } from "./replay";

interface Purchase {
  id: string;
  scenario: string;
  chf: number;
  expected: "approve" | "step_up" | "decline";
  expectedReason: string;
  overLimit: boolean; // above the per-order amount in the instruction, the only thing a plain limit sees
  ours: string;
}

/** What a plain limit catches, what only a rules engine catches: the reference reason, grouped. */
const FAMILY: [string, RegExp][] = [
  ["Over the limit or the budget", /over_order_limit|over_period_budget|possible_split_order/],
  ["Wrong item or unrequested extras", /wrong_item|wrong_size|unrequested_addon|item_outside_purpose/],
  ["Someone else driving the session", /session_not_you/],
  ["Wrong, unknown or imitated seller", /lookalike_shop|new_shop|shop_used_other_card|shop_type_mismatch/],
  ["Return terms not met or not stated", /returns_too_short|final_sale|missing_info/],
  ["Repeated order or text aimed at the agent", /duplicate_order|shop_text_manipulation/],
];
const familyOf = (reason: string) => FAMILY.find(([, re]) => re.test(reason))?.[0] ?? "Other";

export function collect(): Purchase[] {
  const pack = loadDataPack();
  const oracle = new Map(readCsv("reference_decisions.csv").map((r) => [r.authorization_id, r]));
  const out: Purchase[] = [];
  for (const scenarioId of pack.scenarios.keys()) {
    const scenario = pack.scenarios.get(scenarioId)!;
    const limit = compilePolicy(scenario.cardholder_instruction).perOrderLimitChf;
    const ours = new Map(replayScenario(scenarioId).map((r) => [r.source_id, r.decision]));
    const mandate = { mandate_id: `TM_cmp_${scenarioId}`, instruction: scenario.cardholder_instruction, hard_rules: [], uncertainty_policy: "ask" as const };
    for (const attempt of scenarioAttempts(pack, scenarioId)) {
      const ref = oracle.get(attempt.authorization_id);
      if (!ref) continue;
      const chf = buildEvent(pack, attempt, mandate, "cmp").authorization.billing_amount_chf;
      out.push({
        id: attempt.authorization_id,
        scenario: scenarioId,
        chf,
        expected: ref.expected_decision as Purchase["expected"],
        expectedReason: ref.expected_reason ?? "",
        overLimit: limit !== null && chf > limit,
        ours: ours.get(attempt.authorization_id) ?? "approve",
      });
    }
  }
  return out;
}

type Setup = { name: string; caught: (p: Purchase) => boolean };
const SETUPS: Setup[] = [
  { name: "No control", caught: () => false },
  { name: "Plain spending limit", caught: (p) => p.overLimit },
  { name: "Our engine", caught: (p) => p.ours !== "approve" },
];

const chf = (n: number) => `CHF ${n.toLocaleString("en-CH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const sum = (ps: Purchase[]) => ps.reduce((a, p) => a + p.chf, 0);

export function report(purchases: Purchase[]) {
  const risky = purchases.filter((p) => p.expected !== "approve");
  const ordinary = purchases.filter((p) => p.expected === "approve");
  const rows = SETUPS.map((s) => {
    const caught = risky.filter(s.caught);
    const untouched = ordinary.filter((p) => !s.caught(p));
    return { name: s.name, caught: caught.length, unchecked: sum(risky) - sum(caught), untouched: untouched.length };
  });
  const families = FAMILY.map(([name]) => {
    const ps = risky.filter((p) => familyOf(p.expectedReason) === name);
    return { name, risky: ps.length, limit: ps.filter(SETUPS[1].caught).length, ours: ps.filter(SETUPS[2].caught).length };
  }).filter((f) => f.risky > 0);
  return { risky, ordinary, rows, families };
}

export function markdown(purchases: Purchase[]): string {
  const { risky, ordinary, rows, families } = report(purchases);
  const lines = [
    "# Three setups on Viseca's 45 public purchases",
    "",
    `Generated by \`npm run compare\` on ${new Date().toISOString().slice(0, 10)}. A purchase is **risky** when the reference decision is a refusal or a question: ${risky.length} of ${purchases.length}. The other ${ordinary.length} are ordinary.`,
    "",
    "**No control** approves everything. **Plain spending limit** declines only what is above the per-order amount in the customer's instruction, which is what a card limit can see. **Our engine** is the rules engine as shipped, with the customer answering questions as the reference assumes.",
    "",
    "| Setup | Risky purchases stopped or asked | Risky amount paid unchecked | Ordinary purchases approved untouched |",
    "|---|---|---|---|",
    ...rows.map((r) => `| ${r.name} | ${r.caught} of ${risky.length} | ${chf(r.unchecked)} | ${r.untouched} of ${ordinary.length} |`),
    "",
    "## The risky purchases by kind of problem",
    "",
    "| Kind of problem | Risky purchases | A plain limit catches | Our engine catches |",
    "|---|---|---|---|",
    ...families.map((f) => `| ${f.name} | ${f.risky} | ${f.limit} | ${f.ours} |`),
    "",
    "## Every risky purchase",
    "",
    "| Purchase | Scenario | CHF | Reference | Reason | Plain limit | Our engine |",
    "|---|---|---|---|---|---|---|",
    ...risky.map((p) => `| ${p.id} | ${p.scenario} | ${p.chf.toFixed(2)} | ${p.expected} | ${p.expectedReason} | ${p.overLimit ? "caught" : "paid"} | ${p.ours} |`),
    "",
  ];
  return lines.join("\n");
}

/** One slide figure: three bars, one series, labels beside the bars. Light surface, palette from the dataviz skill. */
export function svg(purchases: Purchase[]): string {
  const { risky, rows } = report(purchases);
  const W = 1200, left = 300, barH = 24, gap = 30, top = 170, maxW = 640;
  const H = top + rows.length * (barH + gap) + 40;
  const bars = rows.map((r, i) => {
    const y = top + i * (barH + gap);
    const w = Math.max(4, Math.round((r.caught / risky.length) * maxW));
    const fill = r.name === "Our engine" ? "#2a78d6" : "#eb6834";
    return [
      `<text x="${left - 24}" y="${y + barH / 2 + 8}" text-anchor="end" font-size="24" font-weight="600" fill="#0b0b0b">${r.name}</text>`,
      r.caught > 0 ? `<rect x="${left}" y="${y}" width="${w}" height="${barH}" rx="4" fill="${fill}"><title>${r.name}: ${r.caught} of ${risky.length} risky purchases stopped or asked</title></rect>` : "",
      `<text x="${left + w + 16}" y="${y + barH / 2 + 8}" font-size="24" fill="#0b0b0b">${r.caught} of ${risky.length}</text>`,
    ].join("");
  });
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" font-family="Inter, Segoe UI, Helvetica, Arial, sans-serif">`,
    `<rect width="${W}" height="${H}" fill="#fcfcfb"/>`,
    `<text x="40" y="52" font-size="32" font-weight="700" fill="#0b0b0b">A spending limit catches ${rows[1].caught} of ${risky.length} risky purchases.</text>`,
    `<text x="40" y="92" font-size="32" font-weight="700" fill="#0b0b0b">The rules engine catches ${rows[2].caught}.</text>`,
    `<text x="40" y="128" font-size="19" fill="#52514e">Risky purchases stopped or put to the customer, of ${risky.length} in Viseca's five public scenarios</text>`,
    `<line x1="${left}" y1="${top - 12}" x2="${left}" y2="${H - 30}" stroke="#d9d8d3" stroke-width="2"/>`,
    ...bars,
    `</svg>`,
  ].join("\n");
}

const isMain = process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]));
if (isMain) {
  const purchases = collect();
  const dir = path.resolve(DATA_DIR, "..", "docs", "pitch");
  mkdirSync(dir, { recursive: true });
  writeFileSync(path.join(dir, "comparison.md"), markdown(purchases));
  writeFileSync(path.join(dir, "comparison.svg"), svg(purchases));
  const { risky, rows } = report(purchases);
  for (const r of rows) console.log(`${r.name.padEnd(22)} ${String(r.caught).padStart(2)} of ${risky.length} risky caught · ${chf(r.unchecked).padStart(14)} paid unchecked · ${r.untouched} ordinary untouched`);
  console.log(`written: ${path.join(dir, "comparison.md")} and comparison.svg`);
}
